---
# for more information on redis newrelic configuration, see the official docs:
# https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/redis-monitoring-integration
options:
  extra_packages:
    type: string
    default: 'nri-redis'

  hostname:
    type: string
    default: localhost
    description: Redis server hostname.

  port:
    type: int
    default: 6379
    description: Port where Redis server is listening.

  unix_socket_path:
    type: string
    default: ''
    description: Unix socket path on which Redis server is listening (if set).

  keys:
    type: string
    default: ''
    description: |
      List of the keys for retrieving their lengths.

      See 'keyspace config' in the redis newrelic
      integration docs for more information.

  keys_limit:
    type: int
    default: 30
    description: Max number of the keys to retrieve their lengths.

  password:
    type: string
    default: ''
    description: |
      Password to use when connecting to the Redis server.

      Use only if your Redis server is password-protected.

  environment:
    type: string
    default: 'production'
    description: 'Environment'
